# Generated by Django 4.2.26 on 2026-01-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('user', 'সাধারণ ইউজার'), ('agent', 'এজেন্ট')], default='user', max_length=10),
        ),
    ]
