# Generated by Django 4.2.26 on 2026-01-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0003_userprofile_full_name_userprofile_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
