# Generated by Django 4.2.26 on 2026-01-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0005_alter_userprofile_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='is_available',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='nominee_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to='kothaboli_app.agentprofile'),
        ),
    ]
