# Generated by Django 4.2.26 on 2026-01-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0006_remove_agentprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentprofile',
            name='nominee_name',
        ),
        migrations.RemoveField(
            model_name='agentprofile',
            name='permanent_address',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='identity_document',
            field=models.FileField(blank=True, null=True, upload_to='agents/documents/'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='agents/profiles/'),
        ),
    ]
