# Generated by Django 4.2.26 on 2026-01-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0007_remove_agentprofile_nominee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='nominee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
