# Generated by Django 4.2.26 on 2026-01-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0008_agentprofile_nominee_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='nominee_nid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='relative_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='relative_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
