# Generated by Django 4.2.26 on 2026-01-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0009_agentprofile_is_online_agentprofile_nominee_nid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
