# Generated by Django 4.2.26 on 2026-01-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0010_agentprofile_bio_agentprofile_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
