# Generated by Django 4.2.26 on 2026-01-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0011_agentprofile_rating_agentprofile_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='net_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
