# Generated by Django 4.2.26 on 2026-01-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0012_agentprofile_agreement_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
