# Generated by Django 4.2.26 on 2026-02-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0016_booking_payment_method_booking_sender_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Paid'), ('rejected', 'Payment Failed/Rejected')], default='pending', max_length=20),
        ),
    ]
