# Generated by Django 4.2.26 on 2026-02-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0019_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
