# Generated by Django 4.2.26 on 2026-02-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kothaboli_app', '0020_agentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
